<?php

/**
 * This is the model base class for the table "user_detail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Dealers".
 *
 * Columns in table "user_detail" available as properties of the model,
 * followed by relations of table "user_detail" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $auth_id
 * @property string $auth_provider
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property string $password
 * @property integer $country
 * @property string $state
 * @property integer $location
 * @property string $latitude
 * @property string $longitude
 * @property string $image
 * @property integer $device_type
 * @property string $device_token
 * @property string $created_date
 * @property string $updated_date
 * @property integer $status
 * @property integer $is_active
 * @property integer $is_deleted
 * @property integer $device_settings
 * @property integer $user_type
 * @property string $location_setting
 *
 * @property Offers[] $offers
 * @property Payment[] $payments
 * @property Country $country0
 * @property City $location0
 */
abstract class BaseDealers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_detail';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Dealers|Dealers', $n);
	}

	public static function representingColumn() {
		return 'auth_id';
	}

	public function rules() {
		return array(
			array('auth_id, first_name, last_name, email, phone, password, country, state, location, latitude, longitude, image, device_type, device_token, created_date, user_type', 'required'),
			array('country, location, device_type, status, is_active, is_deleted, device_settings, user_type', 'numerical', 'integerOnly'=>true),
			array('auth_id, password', 'length', 'max'=>250),
			array('auth_provider', 'length', 'max'=>8),
			array('first_name, last_name, email, phone, state, latitude, longitude', 'length', 'max'=>100),
			array('image', 'length', 'max'=>255),
			array('device_token', 'length', 'max'=>500),
			array('location_setting', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('auth_provider, updated_date, status, is_active, is_deleted, device_settings, location_setting', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, auth_id, auth_provider, first_name, last_name, email, phone, password, country, state, location, latitude, longitude, image, device_type, device_token, created_date, updated_date, status, is_active, is_deleted, device_settings, user_type, location_setting', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'offers' => array(self::HAS_MANY, 'Offers', 'user_id'),
			'payments' => array(self::HAS_MANY, 'Payment', 'user_id'),
			'country0' => array(self::BELONGS_TO, 'Country', 'country'),
			'location0' => array(self::BELONGS_TO, 'City', 'location'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'auth_id' => Yii::t('app', 'Auth'),
			'auth_provider' => Yii::t('app', 'Auth Provider'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'email' => Yii::t('app', 'Email'),
			'phone' => Yii::t('app', 'Phone'),
			'password' => Yii::t('app', 'Password'),
			'country' => null,
			'state' => Yii::t('app', 'State'),
			'location' => null,
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
			'image' => Yii::t('app', 'Image'),
			'device_type' => Yii::t('app', 'Device Type'),
			'device_token' => Yii::t('app', 'Device Token'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
			'is_active' => Yii::t('app', 'Is Active'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'device_settings' => Yii::t('app', 'Device Settings'),
			'user_type' => Yii::t('app', 'User Type'),
			'location_setting' => Yii::t('app', 'Location Setting'),
			'offers' => null,
			'payments' => null,
			'country0' => null,
			'location0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('auth_id', $this->auth_id, true);
		$criteria->compare('auth_provider', $this->auth_provider, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('country', $this->country);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('location', $this->location);
		$criteria->compare('latitude', $this->latitude, true);
		$criteria->compare('longitude', $this->longitude, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('device_type', $this->device_type);
		$criteria->compare('device_token', $this->device_token, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('device_settings', $this->device_settings);
		$criteria->compare('user_type', $this->user_type);
		$criteria->compare('location_setting', $this->location_setting, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}