<?php

/**
 * This is the model base class for the table "deal_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DealUser".
 *
 * Columns in table "deal_user" available as properties of the model,
 * followed by relations of table "deal_user" available as properties of the model.
 *
 * @property integer $deal_id
 * @property integer $offer_id
 * @property integer $user_id
 *
 * @property UserDetail $user
 * @property Offers $offer
 */
abstract class BaseDealUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'deal_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DealUser|DealUsers', $n);
	}

	public static function representingColumn() {
		return 'deal_id';
	}

	public function rules() {
		return array(
			array('offer_id, user_id', 'required'),
			array('offer_id, user_id', 'numerical', 'integerOnly'=>true),
			array('deal_id, offer_id, user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'UserDetail', 'user_id'),
			'offer' => array(self::BELONGS_TO, 'Offers', 'offer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'deal_id' => Yii::t('app', 'Deal'),
			'offer_id' => null,
			'user_id' => null,
			'user' => null,
			'offer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('deal_id', $this->deal_id);
		$criteria->compare('offer_id', $this->offer_id);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}