<?php

/**
 * This is the model base class for the table "contactus".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contactus".
 *
 * Columns in table "contactus" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $email
 * @property string $message
 * @property string $send_date
 * @property string $staus
 *
 */
abstract class BaseContactus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contactus';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contactus|Contactuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email, message, send_date, staus', 'required'),
			array('name, email, message', 'length', 'max'=>255),
			array('staus', 'length', 'max'=>1),
			array('id, name, email, message, send_date, staus', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'message' => Yii::t('app', 'Message'),
			'send_date' => Yii::t('app', 'Send Date'),
			'staus' => Yii::t('app', 'Staus'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('send_date', $this->send_date, true);
		$criteria->compare('staus', $this->staus, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}