<?php

/**
 * This is the model base class for the table "city".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "City".
 *
 * Columns in table "city" available as properties of the model,
 * followed by relations of table "city" available as properties of the model.
 *
 * @property integer $city_id
 * @property integer $country_id
 * @property string $city_name
 *
 * @property Country $country
 * @property UserDetail[] $userDetails
 */
abstract class BaseCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'city';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'City|Cities', $n);
	}

	public static function representingColumn() {
		return 'city_name';
	}

	public function rules() {
		return array(
			array('country_id, city_name', 'required'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('city_name', 'length', 'max'=>100),
			array('city_id, country_id, city_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'userDetails' => array(self::HAS_MANY, 'UserDetail', 'location'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'city_id' => Yii::t('app', 'City'),
			'country_id' => null,
			'city_name' => Yii::t('app', 'City Name'),
			'country' => null,
			'userDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('city_name', $this->city_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}