<?php

/**
 * This is the model base class for the table "category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "category" available as properties of the model,
 * followed by relations of table "category" available as properties of the model.
 *
 * @property integer $cat_id
 * @property string $cat_name
 *
 * @property Offers[] $offers
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'cat_name';
	}

	public function rules() {
		return array(
			array('cat_name', 'required'),
			array('cat_name', 'length', 'max'=>100),
			array('cat_id, cat_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'offers' => array(self::HAS_MANY, 'Offers', 'cat_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cat_id' => Yii::t('app', 'Cat'),
			'cat_name' => Yii::t('app', 'Cat Name'),
			'offers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cat_id', $this->cat_id);
		$criteria->compare('cat_name', $this->cat_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}