<?php

/**
 * This is the model base class for the table "favourites".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Favourites".
 *
 * Columns in table "favourites" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $udid
 * @property string $business_id
 * @property string $is_favourite
 * @property string $status
 *
 */
abstract class BaseFavourites extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'favourites';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Favourites|Favourites', $n);
	}

	public static function representingColumn() {
		return 'is_favourite';
	}

	public function rules() {
		return array(
			array('udid, business_id', 'length', 'max'=>10),
			array('is_favourite, status', 'length', 'max'=>1),
			array('udid, business_id, is_favourite, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, udid, business_id, is_favourite, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'udid' => Yii::t('app', 'Udid'),
			'business_id' => null,
			'is_favourite' => Yii::t('app', 'Is Favourite'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('udid', $this->udid, true);
		$criteria->compare('business_id', $this->business_id);
		$criteria->compare('is_favourite', $this->is_favourite, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}