<?php

/**
 * This is the model base class for the table "creditcard".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Creditcard".
 *
 * Columns in table "creditcard" available as properties of the model,
 * followed by relations of table "creditcard" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $cardholder_name
 * @property string $credit_card_no
 * @property string $card_type
 * @property string $expired_date
 * @property string $phone
 * @property string $allow_deduction
 * @property string $renew_date
 *
 * @property Users $user
 */
abstract class BaseCreditcard extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'creditcard';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Creditcard|Creditcards', $n);
	}

	public static function representingColumn() {
		return 'cardholder_name';
	}

	public function rules() {
		return array(
			array('user_id, cardholder_name, credit_card_no, card_type, expired_date, phone, renew_date', 'required'),
			array('user_id, card_type', 'length', 'max'=>10),
			array('cardholder_name', 'length', 'max'=>255),
			array('credit_card_no, phone', 'length', 'max'=>50),
			array('allow_deduction', 'length', 'max'=>1),
			array('allow_deduction', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, cardholder_name, credit_card_no, card_type, expired_date, phone, allow_deduction, renew_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'cardholder_name' => Yii::t('app', 'Cardholder Name'),
			'credit_card_no' => Yii::t('app', 'Credit Card No'),
			'card_type' => Yii::t('app', 'Card Type'),
			'expired_date' => Yii::t('app', 'Expired Date'),
			'phone' => Yii::t('app', 'Phone'),
			'allow_deduction' => Yii::t('app', 'Allow Deduction'),
			'renew_date' => Yii::t('app', 'Renew Date'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('cardholder_name', $this->cardholder_name, true);
		$criteria->compare('credit_card_no', $this->credit_card_no, true);
		$criteria->compare('card_type', $this->card_type, true);
		$criteria->compare('expired_date', $this->expired_date, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('allow_deduction', $this->allow_deduction, true);
		$criteria->compare('renew_date', $this->renew_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}