<?php

/**
 * This is the model base class for the table "state".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "State".
 *
 * Columns in table "state" available as properties of the model,
 * followed by relations of table "state" available as properties of the model.
 *
 * @property integer $state_id
 * @property integer $country_id
 * @property string $state_name
 *
 * @property UserDetail[] $userDetails
 */
abstract class BaseState extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'state';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'State|States', $n);
	}

	public static function representingColumn() {
		return 'state_name';
	}

	public function rules() {
		return array(
			array('country_id, state_name', 'required'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('state_name', 'length', 'max'=>100),
			array('state_id, country_id, state_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'userDetails' => array(self::HAS_MANY, 'UserDetail', 'state'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'state_id' => Yii::t('app', 'State'),
			'country_id' => Yii::t('app', 'Country'),
			'state_name' => Yii::t('app', 'State Name'),
			'userDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('state_name', $this->state_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}