<?php

/**
 * This is the model base class for the table "currency".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Currency".
 *
 * Columns in table "currency" available as properties of the model,
 * followed by relations of table "currency" available as properties of the model.
 *
 * @property integer $currency_id
 * @property string $currency_name
 *
 * @property Offers[] $offers
 */
abstract class BaseCurrency extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'currency';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Currency|Currencies', $n);
	}

	public static function representingColumn() {
		return 'currency_name';
	}

	public function rules() {
		return array(
			array('currency_name', 'required'),
			array('currency_name', 'length', 'max'=>100),
			array('currency_id, currency_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'offers' => array(self::HAS_MANY, 'Offers', 'currency_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'currency_id' => Yii::t('app', 'Currency'),
			'currency_name' => Yii::t('app', 'Currency Name'),
			'offers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('currency_id', $this->currency_id);
		$criteria->compare('currency_name', $this->currency_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}